### ISSUE TITLE
使用emsdk工具编译ffmpeg源代码错误

### ISSUE THREAD

**Issue by Qianxunha** [goldvideo/decoder_wasm#1]
博主你好，使用emsdk工具编译ffmpeg-4.1.5源代码编译不过，请问怎么解决
![image](https://user-images.githubusercontent.com/55270103/81532561-2cd93a80-9397-11ea-9747-2bf03679796c.png)
1）报错地方如下，找不到/opt/tar-download/emsdk/upstream/bin/wasm-opt: /usr/lib64/libc.so.6: version `GLIBC_2.18' not found (required by /opt/tar-download/emsdk/upstream/bin/wasm-opt)
![image](https://user-images.githubusercontent.com/55270103/81532667-5a25e880-9397-11ea-9dbd-cc5fa5e5362a.png)
2）emsdk工具版本 1.39.15
![image](https://user-images.githubusercontent.com/55270103/81532737-788be400-9397-11ea-94d8-6be3cbfa3067.png)

**Comment by snxly** [comment]
Google一下你的报错信息，有不少解决办法。

**Comment by Qianxunha** [comment]
@snxly  网上找遍了，都没有找到，感觉是emsdk工具问题

**Comment by snxly** [comment]
![image](https://user-images.githubusercontent.com/15939467/81533727-44192780-9399-11ea-88fe-2369db6d6d9f.png)

**Comment by Qianxunha** [comment]
@snxly 谢谢博主，问题已解决

**Comment by xgene** [comment]
千辛万苦将ffmpeg编译搞定了！ 但是编译wasm时老报错
wasm-ld: error: /tmp/emscripten_temp_k8oaxqc5/decode_video_0.o: undefined symbol:av_log_set_callback
还有很多这类错误，我的是在macOS下

**Comment by snxly** [comment]
av_log_set_callback 是ffmpeg的api，用来记log用的。decode_video.c里用到了这个api。

**Comment by snxly** [comment]
av_log_set_callback 是ffmpeg的api，用来记log用的。
decode_video.c里用到了这个api。
检查下 ffmpeg是否编译成功，特别是shell脚本里用到的那几个。
